custom:
  auth-server: ${AUTH_SERVER:}
logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  servlet:
    context-path: /alpha-sound
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    tomcat:
      connection-properties: stringtype=unspecified
    url: jdbc:postgresql://192.168.0.100:5432/alpha_sound
    username: postgres
    password: 123456
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        hb2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: static/i18n/message
  web:
    locale: en_US
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
